### ISSUE TITLE
HubSpot UI Library integration with React projects

### ISSUE THREAD

**Issue by dgonzalezr** [HubSpot/canvas#3]
Hi guys,

Maybe it's a stupid question (most probably that is not possible), but didn't find nothing about. So, I'm asking if there is any way to integrate HubSpot UI Library in a React project? 🤔

Thank you in advance.

**Comment by TrevorBurnham** [comment]
What exactly did you have in mind for this integration?

**Comment by TrevorBurnham** [comment]
Short answer is "no." We've put our plans to open-source our UI Library on indefinite hold.

**Comment by francisconeves97** [comment]
Any new update on your plans? You have an awesome design system!

**Comment by Nikit-Singh** [comment]
+1
Any new updates?
I really loved the design system. :)

**Comment by ozgursarioglan** [comment]
I like your design system very much.
When will you make it available?

**Comment by pedrosimao** [comment]
Would really be great to have it open-sourced!
