### ISSUE TITLE
Hubspot Canvas License

### ISSUE THREAD

**Issue by cpheimbach** [HubSpot/canvas#4]
I was wondering about the license situation of the canvas. 

I can see in the core/package.json that it is specified to be MIT but wanted to double check since no license file is specified in the parent folder.

Cheers and apologies if I've missed spotting that information somewhere else.

**Comment by TrevorBurnham** [comment]
@cpheimbach Sorry about that! This repo is an abandoned project. I'm sure we'd be happy to MIT-license it, but tbh there isn't anything worth forking here. 😅
